name: sangisdownload
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.9.24=h5b45459_0
  - libffi=3.4.2=h8ffe710_5
  - libsqlite=3.39.3=hcfcfb64_0
  - libzlib=1.2.12=hcfcfb64_3
  - openssl=3.0.5=hcfcfb64_2
  - pip=22.2.2=pyhd8ed1ab_0
  - python=3.10.6=hcf16a7b_0_cpython
  - setuptools=65.4.0=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - tzdata=2022d=h191b570_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_7
  - vs2015_runtime=14.29.30139=h890b9b1_7
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - pip:
    - certifi==2022.9.24
    - charset-normalizer==2.1.1
    - idna==3.4
    - lxml==4.9.1
    - pyparsing==3.0.9
    - requests==2.28.1
    - twill==3.0.2
    - urllib3==1.26.12
prefix: 'C:\Anaconda\envs\sangisdownload'
